# Generated by Django 3.2 on 2021-04-19 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('current_players', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 17, 29, 5, 709609, tzinfo=utc))),
                ('game_creator', models.CharField(default='', max_length=50)),
                ('is_over', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='main.Tag')),
            ],
        ),
    ]
